### ISSUE TITLE
Change ➗ to 🖊️ in edit messages

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Notify#2]
Знак деления при редактировании событий вызывает небольшой ступор, все же правильнее кажется использование карандаша.
Обсуждение приветствуется.

**Comment by wndenis** [comment]
Яростно поддерживаю

**Comment by dmromanov98** [comment]
Как только так сразу

**Comment by wndenis** [comment]
Это всего один символ
